version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mini_erp_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: mini_erp_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mini_erp_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: mini_erp_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: production
      JWT_SECRET: super_secret_mini_erp_crm_jwt_key_2026
      JWT_EXPIRES_IN: 24h
      DATABASE_URL: postgresql://postgres:postgrespassword@postgres:5432/mini_erp_db?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npx prisma db push --accept-data-loss && npx ts-node prisma/seed.ts && node dist/server.js"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: mini_erp_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
